source 'https://rubygems.org'


gem 'rails', '4.1.7'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'

gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'numbers_in_words', '~> 0.4.0'
gem 'angularjs-rails'
gem 'bower-rails' 

group :development, :test do
  gem 'byebug'
  gem 'spring'
  gem 'factory_girl_rails', '~> 4.0'
  gem 'capybara'
end

gem 'bootstrap-sass', '~> 3.3.4'
gem 'haml-rails'

group :development, :test do
  gem 'rspec-rails'
end
